package com.extractor.unraveldocs.ocrprocessing.model;

import com.extractor.unraveldocs.ocrprocessing.datamodel.ContentFormat;
import com.extractor.unraveldocs.ocrprocessing.datamodel.OcrStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.OffsetDateTime;

@Entity
@Table(name = "ocr_data")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class OcrData {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @Column(name = "document_id", nullable = false, unique = true)
    private String documentId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private OcrStatus status;

    @Lob
    @Column(name = "extracted_text", columnDefinition = "TEXT")
    private String extractedText;

    @Lob
    @Column(name = "edited_content", columnDefinition = "TEXT")
    private String editedContent;

    @Enumerated(EnumType.STRING)
    @Column(name = "content_format", length = 20)
    private ContentFormat contentFormat;

    @Column(name = "edited_by")
    private String editedBy;

    @Column(name = "edited_at")
    private OffsetDateTime editedAt;

    @Column(name = "error_message")
    private String errorMessage;

    @Column(name = "ai_summary", columnDefinition = "TEXT")
    private String aiSummary;

    @Column(name = "document_type", length = 50)
    private String documentType;

    @Column(name = "ai_tags", length = 500)
    private String aiTags; // Comma-separated tags generated by AI classification

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;
}
